name: Jacoco Test With Github Action

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Test with Gradle Wrapper
      run: ./gradlew test

    - name: Create Test Coverage Report with Jacoco
      uses: Madrapps/jacoco-report@v1.7.1
      with:
        title: Test Coverage Report
        paths: ${{ github.workspace }}/build/jacocoReport/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 50
